id: A18941F44
title: 'The Vajra Verses: A Prayer of the Fierce Inner Heat'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 03:38:00.045274
  last_modified_at: 2022-03-01 03:38:00.045282
